<!-- View All Patterns in a Pattern Sub-Type -->
<div class="sg-main" role="main">
    <!-- Patterns -->
    <div id="sg-patterns">
        <?php foreach ($partials as $partial): ?>
            <?php if (isset($partial['patternSectionSubtype'])): ?>
                <?php require $partial['patternSectionSubtype']; ?>
            <?php else: ?>
                <?php require "patternSection.phtml"; ?>
            <?php endif; ?>
        <?php endforeach; ?>
    </div> <!--end #sg-patterns-->
</div><!--end .sg-main-->